site_name: dataview
# site_url: https://docs.k.avito.ru/iaas-docs-user-guide/
repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: blob/master/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
 - Home: index.md
 - Getting Started: getting-started.md
 - Examples: examples/

plugins:
 - search
 - dataview
  # - awesome-pages:
  #     collapse_single_pages: false
  #     strict: true
  # - search:
  #     min_search_length: 3
  #     lang:
  #       - en
  #       - ru
  # - glightbox

# nav:
#   - 'Начало': index.md
#   - 'Примеры': tutorials
#   - 'Ресурсы': resources

# extra:
#   repo_icon: bitbucket

markdown_extensions:
  - toc
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
     use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click
  - meta
  # - dataview
  # - admonition
  # - footnotes
  # - attr_list
  # - sane_lists
  # - codehilite:
  #     guess_lang: false
  # - toc:
  #     slugify: !!python/name:daas_extensions.slugify
  #     permalink: '#'
  # - pymdownx.arithmatex
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.keys

# After upgrading to material design version 9, uncomment following lines
#   - pymdownx.emoji:
# #      emoji_index: !!python/name:material.extensions.emoji.twemoji
# #      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#       emoji_index: !!python/name:pymdownx.emoji.gemoji
#       emoji_generator: !!python/name:pymdownx.emoji.to_svg

  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  # - pymdownx.inlinehilite
  # - pymdownx.magiclink
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences:
  #     preserve_tabs: true
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_div_format
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
  # - pymdownx.tabbed
  # - attr_list
  # - md_in_html

